// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Pronto.Infrastructure.Models;

/// <summary>
/// Pronto database console
/// </summary>
public partial class ProntoContext : DbContext
{
    public static string ConnectionString = "";

    public virtual DbSet<Chunk> Chunks { get; set; }

    public virtual DbSet<CassandraEmbedding> Embeddings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Chunk>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("pk__Chunks")
                .IsClustered(false);

            entity.ToTable("Chunks");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<CassandraEmbedding>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("pk__Embeddings")
                .IsClustered(true);

            entity.ToTable("Embeddings");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.ChunkId).ValueGeneratedNever();
            entity.Property(e => e.VectorValueContent).HasColumnName("Vector_Value_Content");
            entity.Property(e => e.VectorValueId).HasColumnName("Vector_Value_Id");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    /// <summary>
    /// Overridable method
    /// </summary>
    /// <param name="optionsBuilder"></param>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(ConnectionString);
    }
}